export const platforms = [
    "PC (Microsoft Windows)", "PlayStation 5", "PlayStation 4", "Xbox Series X|S", 
    "Xbox One", "Nintendo Switch", "PlayStation 3", "Xbox 360", "PlayStation 2", 
    "Nintendo 64", "Nintendo DS", "Game Boy Advance", "Game Boy Color", 
    "Nintendo GameCube", "Wii", "Super Nintendo Entertainment System", 
    "Sega Mega Drive/Genesis", "Commodore 64/128/MAX", "Amiga", "DOS", 
    "Android", "iOS", "SteamVR", "Oculus Quest", "Oculus Rift", 
    "PlayStation VR2", "Meta Quest 2", "Mac", "Linux", "Web browser", 
    "Atari 2600", "Atari ST/STE", "Sega Saturn", "Atari 7800", "Neo Geo AES", 
    "Neo Geo MVS", "TurboGrafx-16/PC Engine", "Amstrad CPC", "MSX", 
    "ZX Spectrum", "Game Boy", "Commodore VIC-20", "Sega Game Gear", 
    "WonderSwan Color", "WonderSwan", "ColecoVision", "Philips CD-i", 
    "Commodore PET", "BBC Microcomputer System", "Apple II", "Sharp X68000", 
    "Turbografx-16/PC Engine CD", "Neo Geo Pocket Color", "Neo Geo Pocket", 
    "PlayStation Portable", "PlayStation Vita", "Intellivision", "Atari Lynx", 
    "Virtual Boy", "3DO Interactive Multiplayer", "Virtual Console", 
    "Gizmondo", "Game.com", "Oculus Go", "Leapster", "LeapTV", 
    "Famicom Disk System", "Family Computer", "Game & Watch", 
    "Playdia", "Sega CD", "Sega Pico", "Atari Jaguar", "Atari Jaguar CD", 
    "Sega 32X", "PDP-11", "PDP-8", "DEC GT40", "TRS-80", 
    "TRS-80 Color Computer", "Fairchild Channel F", "Commodore Plus/4", 
    "Tatung Einstein", "SwanCrystal", "PocketStation", "Meta Quest 3", 
    "Playdate", "Gamate", "Casio Loopy", "Tomy Tutor / Pyuta / Grandstand Tutor", 
    "M.A.M.E. (arcade)", "Dragon 32/64", "Arcadia 2001", "Super A'Can", 
    "V.Smile", "Arduboy", "Sharp MZ-2200", "Windows Mobile", 
    "Windows Mixed Reality", "Blu-ray Player", "DVD Player", 
    "BlackBerry OS", "Amazon Fire TV", "Google Stadia", "Ouya", 
    "Sega Master System/Mark III", "Terebikko / See 'n Say Video Phone", 
    "HP 3000", "HP 2100", "Call-A-Computer time-shared mainframe computer system", 
    "EDSAC", "PLATO", "Microvision", "Odyssey", "Odyssey 2 / Videopac G7000", 
    "PDP-7", "PDP-10", "Z88", "SDS Sigma 7", "Commodore 16", "Commodore 128", 
    "Bally Astrocade", "Super Famicom", "Philips CD-i", "Casio Loopy", 
    "Legacy Computer", "Handheld Electronic LCD", "Legacy Mobile Device", 
    "Analogue electronics", "Apple Pippin", "PlayStation", 
    "HyperScan", "Mega Duck/Cougar Boy", "Watara/QuickShot Supervision", 
    "PDP-1", "Analogue electronics", "PlayStation VR", "Casio Loopy", 
    "OOParts", "Zeebo", "N-Gage", "Gamate", "Zeebo", "Gizmondo", 
    "Turbografx-16/PC Engine CD", "Gizmondo", "Daydream", "V.Smile", 
    "PlayStation Portable", "PlayStation Vita", "Atari 5200", "Commodore CDTV", 
    "PC-FX", "MSX2", "Sharp X1", "FM Towns", "FM-7", "PC-9800 Series", 
    "PC-8800 Series", "Commodore 16", "Commodore 128", "Game.com", 
    "Analogue electronics", "Call-A-Computer time-shared mainframe computer system"
];
