import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import UserDataFetcher from "@/src/context/userDataFetcher";
import { ThemeProvider } from "@/src/context/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GameHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <SessionProvider>
          <UserDataFetcher>
            <body className={`${inter.className} bg-background text-color_text transition-colors duration-200`}>
              {children}
            </body>
          </UserDataFetcher>
        </SessionProvider>
      </ThemeProvider>
    </html>
  );
}